apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destination:
    namespace: ingress-nginx
    name: in-cluster
  project: idp
  syncPolicy:
    automated:
      prune: false
      allowEmpty: true
      selfHeal: true
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: ^4.1.0
    helm:
      releaseName: internal-ingress
      values: |
        controller:
          ingressClass: systeminternalingress
          ingressClassResource:
            name: systeminternalingress

          replicaCount: 2

          metrics:
            enabled: true
            service:
              annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "10254"

          publishService:
            enabled: true

          config:
            force-ssl-redirect: "true"
            use-proxy-protocol: "true"

          service:
            targetPorts:
              https: http

            annotations:
              external-dns.alpha.kubernetes.io/hostname: "*.ivas-idp.de"
              service.beta.kubernetes.io/aws-load-balancer-alpn-policy: None
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
              service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
              service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
              service.beta.kubernetes.io/aws-load-balancer-scheme: internal
              service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:943239102098:certificate/106d832e-8bcb-4b7a-a6a5-c3225c812e07
              service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
              service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
              service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "proxy_protocol_v2.enabled=true,deregistration_delay.timeout_seconds=120,deregistration_delay.connection_termination.enabled=true"
              service.beta.kubernetes.io/aws-load-balancer-type: external
