apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: keycloak
    server: 'https://kubernetes.default.svc'
  project: idp
  syncPolicy:
    automated:
      prune: false
      allowEmpty: true
      selfHeal: true
  source:
    chart: keycloak
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.1.5
    helm:
      releaseName: keycloak
      values: |
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/configuration-snippet: |
              proxy_set_header Host keycloak.ivas-idp.de;
            nginx.ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/cors-allow-origin: "http://keycloak.ivas-idp.de"
          hostname: "keycloak.ivas-idp.de"
        clusterDomain: "keycloak.ivas-idp.de"
        rbac:
          create: true
        auth:
          adminUser: keycloak
          adminPassword: keycloak
          managementUser: david
          managementPassword: david
        cache:
          enabled: false
        proxy: edge
        resources:
          requests:
            cpu: 0.5
            memory: 512Mi
          limits:
            cpu: 2
            memory: 2Gi

        podSecurityContext:
          enabled: true
          fsGroup: 0

        containerSecurityContext:
          enabled: true
          runAsUser: 0
          runAsNonRoot: false

        extraEnvVars:
          - name: KEYCLOAK_PRODUCTION
            value: "true"
          - name: KC_HOSTNAME
            value: "keycloak.ivas-idp.de"
          - name: KC_HOSTNAME_STRICT
            value: "false"
          - name: KC_HOSTNAME_STRICT_HTTPS
            value: "true"
          - name: KC_LOG_LEVEL
            value: "DEBUG"
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"

        metrics:
          enabled: true

        postgresql:
          auth:
            password: keycloak
        
        keycloakConfigCli:
          enabled: true
          configuration:
            realm1.json: |
              {
                "realm": "realm1",
                "clients": []
              }
